version: '3'

services:
  mongodb:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:management
    expose:
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
